### ISSUE TITLE
Kopieren von Content-Element kopiert den Text nicht mit

### ISSUE THREAD

**Issue by MacKP** [hofff/contao-facebook-pixel#1]
Eventuell selbes Schema: Wenn ich das Content Element änder (auf Text und dann zurück), dann ist der Text auch nicht mehr vorhanden.

Viele Grüße

**Comment by dmolineus** [comment]
Kann ich im aktuellen Stand nicht nachvollziehen. @MacKP tritt das Problem bei dir mit der aktuellen Version 2.0.0-rc1 noch auf?

**Comment by MacKP** [comment]
Kann ich aktuell leider nicht nachstellen (gerade keine Möglichkeit). VOn daher wäre ich dafür dass Issue erst mal zu schließen, da es ja bei dir auch nicht mehr vorhanden zu sein scheint ;-)
