### ISSUE TITLE
Kompatibel zu Contao 4.11

### ISSUE THREAD

**Issue by dp-designpilot** [hofff/contao-facebook-pixel#3]
Hallo Nicky

Ist die Erweiterung **_contao-facebook-pixel_** kompatibel zu Contao 4.11.2 ?? Weil ich hab hier einige Fehler die es mir im Contao Manager ausgibt (gottseidank habe ich das nur auf den TEST Button geklickt)

Problem 1
    - hofff/contao-facebook-pixel[2.1.0, ..., 2.1.2] require symfony/dependency-injection ^3.3 || ^4.0 -> satisfiable by symfony/dependency-injection[v3.3.0, ..., v3.4.47, v4.0.0, ..., v4.4.21].
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.4.21.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.4.20.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.4.19.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.4.18.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.4.17.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.4.16.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.4.15.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.4.14.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.4.13.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.4.12.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.4.11.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.4.10.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.4.9.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.4.8.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.4.7.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.4.6.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.4.5.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.4.4.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.4.3.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.4.2.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.4.1.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.4.0.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.3.11.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.3.10.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.3.9.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.3.8.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.3.7.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.3.6.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.3.5.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.3.4.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.3.3.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.3.2.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.3.1.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.3.0.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.2.12.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.2.11.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.2.10.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.2.9.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.2.8.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.2.7.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.2.6.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.2.5.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.2.4.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.2.3.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.2.2.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.2.1.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.2.0.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.1.12.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.1.11.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.1.10.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.1.9.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.1.8.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.1.7.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.1.6.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.1.5.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.1.4.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.1.3.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.1.2.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.1.1.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.1.0.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.0.15.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.0.14.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.0.13.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.0.12.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.0.11.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.0.10.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.0.9.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.0.8.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.0.7.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.0.6.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.0.5.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.0.4.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.0.3.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.0.2.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.0.1.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v4.0.0.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.47.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.46.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.45.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.44.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.43.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.42.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.41.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.40.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.39.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.38.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.37.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.36.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.35.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.34.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.33.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.32.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.31.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.30.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.29.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.28.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.27.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.26.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.25.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.24.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.23.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.22.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.21.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.20.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.19.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.18.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.17.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.16.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.15.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.14.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.13.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.12.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.11.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.10.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.9.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.8.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.7.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.6.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.5.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.4.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.3.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.2.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.1.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.4.0.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.3.18.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.3.17.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.3.16.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.3.15.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.3.14.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.3.13.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.3.12.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.3.11.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.3.10.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.3.9.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.3.8.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.3.7.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.3.6.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.3.5.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.3.4.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.3.3.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.3.2.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.3.1.
    - symfony/debug-bundle v5.2.4 conflicts with symfony/dependency-injection v3.3.0.
    - contao/manager-bundle 4.11.2 requires symfony/debug-bundle 4.4.* || 5.2.* -> satisfiable by symfony/debug-bundle[v5.2.4].
    - contao/manager-bundle is locked to version 4.11.2 and an update of this package was not requested.
    - Root composer.json requires hofff/contao-facebook-pixel ^2.1 -> satisfiable by hofff/contao-facebook-pixel[2.1.0, 2.1.1, 2.1.2].
 
[1105.6MiB/7.99s] WARNING Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems. WARNING

**Comment by frontendschlampe** [comment]
wir haben unsererseits keine Probleme mit der Installation. Bitte führe eine Komplettaktualisierung oder ein `composer update` durch.

**Comment by dp-designpilot** [comment]
Hallo Nicky

Anbei noch meine composer.json wo ist denn das Problem, weil ich hab ja über den Contao Manager das Update gemacht

{
    "type": "project",
    "require": {
        "christianbarkowsky/contao-tiny-compress-images": "^1.0",
        "codefog/contao-elements-filter": "^1.1",
        "codefog/contao-social_images": "^3.7",
        "contao/calendar-bundle": "4.11.*",
        "contao/comments-bundle": "4.11.*",
        "contao/conflicts": "*@dev",
        "contao/faq-bundle": "4.11.*",
        "contao/listing-bundle": "4.11.*",
        "contao/manager-bundle": "4.11.*",
        "contao/news-bundle": "4.11.*",
        "contao/newsletter-bundle": "4.11.*",
        "dieschittigs/contao-recaptcha": "^1.2",
        "dklemmt/contao_dk_mmenu": "^3.2",
        "do-while/contao-backupdb-bundle": "^1.4",
        "e-spin/form-newsletter-bundle": "^1.0",
        "erdmannfreunde/contao-grid-bundle": "^1.0",
        "erdmannfreunde/euf_hero": "^2.0",
        "erdmannfreunde/euf_overlay": "^1.3",
        "fritzmg/contao-facebook-js-sdk": "^3.2",
        "jrgregory/m17-sticky-backend-footer": "^2.0",
        "markocupic/contao-crm-bundle": "^1.0",
        "markocupic/preloader-overlay": "^1.0",
        "numero2/contao-opengraph3": "^4.1",
        "oveleon/contao-company-bundle": "^1.2",
        "oveleon/contao-member-notification": "^1.0",
        "oveleon/contao-recommendation-bundle": "^1.0",
        "plenta/contao-countup-bundle": "^1.0",
        "srhinow/themecontent-bundle": "^0.2.0",
        "terminal42/contao-changelanguage": "^3.1",
        "terminal42/contao-easy_themes": "^2.2",
        "terminal42/contao-folderpage": "^2.0",
        "terminal42/contao-leads": "^1.4",
        "terminal42/contao-pageimage": "^4.0",
        "terminal42/notification_center": "^1.5"
    },
    "extra": {
        "contao-component-dir": "assets"
    },
    "scripts": {
        "post-install-cmd": [
            "Contao\\ManagerBundle\\Composer\\ScriptHandler::initializeApplication"
        ],
        "post-update-cmd": [
            "Contao\\ManagerBundle\\Composer\\ScriptHandler::initializeApplication"
        ]
    },
    "conflict": {
        "symfony/framework-bundle": ">=5"
    }
}

Grüsse
Didier
